site_name: AutolabJS
theme: 'material'
pages:
  - Home: 'index.md'
  - AutolabJS:
    - Home:  'AutolabJS.md'
    - AutolabJS v0.1.0: 
      - Home : 'AutolabJS v0.1.0/AutolabJS-v010.md'
      - Deployment Tutorial :
        - Deployment-on-Single-Machine: 'AutolabJS v0.1.0/v0.1-Deploying-using-Docker.md'
        - On two machines : 'AutolabJS v0.1.0/v0.1-Two-Machines.md'
        - On Azure cloud : 'AutolabJS v0.1.0/v0.1-On-Azure-Cloud.md'     
        - JSON details : 'AutolabJS v0.1.0/v0.1-JSON-files-documetation.md'
      - Tutorials for Lab Authors :
        - Creating a Lab : 'AutolabJS v0.1.0/v0.1-Creating-and-Modifying-a-lab.md'
        - Automate lab/user : 'AutolabJS v0.1.0/v0.1-Automate-Lab-Create-Update-Delete-Activities.md'
      - Tutorials for Students :
        - Making a Submission : 'AutolabJS v0.1.0/v0.1-Making-a-Submission.md'
        - Post lab self evaluation : 'AutolabJS v0.1.0/v0.1-Post-lab-self-evaluation.md'
    - AutolabJS v0.2.0:
      - Home: 'AutolabJS v0.2.0/AutolabJS-v020.md'
      - Deployment Tutorial :
        - Deployment-on-Single-Machine: 'AutolabJS v0.2.0/v0.2.0-Deployment-on-Single-Machine.md'
        - On two machines : 'AutolabJS v0.2.0/v0.2.0-Deployment-on-Two-Machines.md'
        - On Azure cloud : 'AutolabJS v0.2.0/v0.2.0-On-Azure-Cloud.md'     
        - Container Maintenance : 'AutolabJS v0.2.0/v0.2.0-Container-Maintenance.md'
        - JSON details : 'AutolabJS v0.2.0/v0.2.0-JSON-files-documetation.md'
        - Uninstall AutolabJS : 'AutolabJS v0.2.0/v0.2.0-Uninstall-Autolab.md'
        - FAQ:
          - Student: 'AutolabJS v0.2.0/FAQs/v0.2.0-Student-FAQs.md'
          - Instructor : 'AutolabJS v0.2.0/FAQs/v0.2.0-Instructor-FAQs.md'
          - Administrator: 'AutolabJS v0.2.0/FAQs/v0.2.0-Administrator-FAQs.md'   
      - Tutorials for Lab Authors :
        - Using AutolabJS-Initial Configuration : 'AutolabJS v0.2.0/v0.2.0-Using-Autolab-in-a-Course.md'
        - Creating a Lab : 
          - Home : 'AutolabJS v0.2.0/v0.2.0-Creating-and-Modifying-a-lab.md'
          - JUnit-based labs: 'AutolabJS v0.2.0/v0.2.0-Creating-Labs-for-JUnit-Tests.md'
          - Input-Output (IO) tests using:
            - Source code : 'AutolabJS v0.2.0/v0.2.0-Creating-Labs-for-IO-Tests-with-Source-Code.md'
            - Compiled binaries: 'AutolabJS v0.2.0/v0.2.0-Creating-Labs-for-IO-Tests-with-Compiled-Binaries.md'
        - Manage Course : 'AutolabJS v0.2.0/v0.2.0-Manage-Course.md'
      - Tutorials for Students :
        - Making a Submission : 
          - Home : 'AutolabJS v0.2.0/v0.2.0-Making-a-Submission.md'
          - Unit tests : 'AutolabJS v0.2.0/v0.2.0-Unit-Tests.md'
          - Input-Output (IO) tests using :
            - Source code : 'AutolabJS v0.2.0/v0.2.0-IO-Tests.md'
            - Compiled binaries : 'AutolabJS v0.2.0/v0.2.0-IO-Tests-Binaries.md'
        - Post lab self evaluation : 'AutolabJS v0.2.0/v0.2.0-Post-lab-self-evaluation.md'
  - AutloabJS Coding Standards : 'AutolabJS-coding-standards.md'
  - AutolabCLI: 'autolabcli.md'
  - Documentation: 'docs.md'
  - AutolabWebsite: 'website.md'
extra:
  palette:
    primary: 'blue'
    accent: 'light blue'
extra:
  social:
    - type: 'github'
link: 'https://github.com/AutolabJS'
